name: 打包应用并上传阿里云

on:
    push:
        branches:
            - master

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        steps:
            - name: 迁出代码
              # 使用action库  actions/checkout获取源码
              uses: actions/checkout@master
            - name: 压缩项目
              run: tar  -zcvf second-website.tgz .
            - name: 删除阿里云已经部署的项目
              uses: appleboy/ssh-action@master
              with:
                  # 服务器ip
                  host: ${{ secrets.HOST }}
                  # 服务器登录用户名
                  username: ${{ secrets.HOST_USERNAME }}
                  # 服务器登录密码
                  password: ${{ secrets.HOST_PASSWORD }}
                  key: ${{ secrets.HOST_SSH_KEY }}
                  # 服务器ssh端口
                  port:  ${{ secrets.HOST_PORT }}
                  script: |
                    cd /root/go/src/second-website
                    rm -rf ./*    
            - name: 将项目上传到阿里云服务器
              uses: garygrossgarten/github-action-scp@release
              with:
                local: second-website.tgz
                remote: /root/go/src/second-website/second-website.tgz
                host: ${{ secrets.HOST }}
                username: ${{ secrets.HOST_USERNAME }}
                password: ${{ secrets.HOST_PASSWORD }}
            - name: 发布到阿里云
              uses: appleboy/ssh-action@master
              with:
                  # 服务器ip
                  host: ${{ secrets.HOST }}
                  # 服务器登录用户名
                  username: ${{ secrets.HOST_USERNAME }}
                  # 服务器登录密码
                  password: ${{ secrets.HOST_PASSWORD }}
                  key: ${{ secrets.HOST_SSH_KEY }}
                  # 服务器ssh端口
                  port:  ${{ secrets.HOST_PORT }}
                  script: |
                    cd /root/go/src/second-website
                    tar -xzvf second-website.tgz
                    sh deploy.sh

            
                  