name: 打包应用并上传阿里云

on:
    push:
        branches:
            - master

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        steps:
            - name: 迁出代码
              # 使用action库  actions/checkout获取源码
              uses: actions/checkout@master
            # 第二步：打包构建
            - run: tar -zcvf second-webbbsite.tgz .
            - name: 将项目上传到阿里云服务器
              uses: garygrossgarten/github-action-scp@release
              with:
                local: second-webbbsite.tgz
                remote: /root/go/src
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USER }}
                password: ${{ secrets.SERVER_PASS }}
            
                  